import heroCoffee from '@/assets/hero-coffee.jpg';
import espressoImg from '@/assets/espresso.jpg';
import cappuccinoImg from '@/assets/cappuccino.jpg';
import icedCoffee from '@/assets/iced-coffee.jpg';
import croissant from '@/assets/croissant.jpg';

// Menu Assets
import sandwichImg from '@/assets/menu/sandwich.png';
import waffleImg from '@/assets/menu/waffle.png';
import frappeImg from '@/assets/menu/frappe.png';
import mojitoImg from '@/assets/menu/mojito.png';

// New Food Assets
import pizzaImg from '@/assets/menu/pizza.png';
import pastaImg from '@/assets/menu/pasta.png';
import soupImg from '@/assets/menu/soup.png';
import mocktailImg from '@/assets/menu/mocktail.png';

import { MenuItem } from './store';

export const menuItems: MenuItem[] = [
  // --- SOUP ---
  {
    id: 'soup1',
    name: 'Minestrone',
    price: 265,
    category: 'soup',
    image: soupImg,
    description: 'A hearty Italian classic loaded with fresh vegetables, pasta, and herbs simmered in a rich tomato broth.',
    isAvailable: true,
  },
  {
    id: 'soup2',
    name: 'Baked Onion Soup',
    price: 295,
    category: 'soup',
    image: soupImg,
    description: 'Slow-cooked caramelized onions in a deep, savory broth, topped with a layer of melted cheese and crisp baked bread.',
    isAvailable: true,
  },
  {
    id: 'soup3',
    name: 'Fresh Tomato Basil',
    price: 295,
    category: 'soup',
    image: soupImg,
    description: 'Velvety smooth blend of ripe tomatoes and fresh basil, gently simmered to perfection.',
    isAvailable: true,
  },

  // --- APPETIZER & SALADS ---
  {
    id: 'app1',
    name: 'Mozzarella Tomato Basil Bruschetta',
    price: 315,
    category: 'appetizers',
    image: pizzaImg,
    description: 'Toasted sourdough bread topped with creamy fresh mozzarella, ripe cherry tomatoes, and sweet basil leaves.',
    isAvailable: true,
  },
  {
    id: 'app2',
    name: 'Smashed Guacamole Crostini',
    price: 325,
    category: 'appetizers',
    image: sandwichImg,
    description: 'Toasted sourdough topped with fresh smashed avocado, lime, jalapeño, and juicy cherry tomatoes.',
    isAvailable: true,
  },
  {
    id: 'app3',
    name: 'Fire Fries',
    price: 245,
    category: 'appetizers',
    image: sandwichImg,
    description: 'Crispy thin-cut potato fries tossed in sea salt and our signature spicy seasoning.',
    isAvailable: true,
  },
  {
    id: 'app4',
    name: 'Truffle & Parmesan Crisps',
    price: 335,
    category: 'appetizers',
    image: pizzaImg,
    description: 'Crispy thin potato chips drizzled with aromatic truffle oil and topped with fresh grated Parmesan.',
    isAvailable: true,
  },
  {
    id: 'app5',
    name: 'Garlic Bread With Cheese Dip',
    price: 285,
    category: 'appetizers',
    image: croissant,
    description: 'Warm, buttery garlic bread served with a side of creamy molten cheese dip.',
    isAvailable: true,
  },
  {
    id: 'app6',
    name: 'Caesar Salad',
    price: 315,
    category: 'appetizers',
    image: saladImg(),
    description: 'Crisp romaine lettuce tossed in our creamy Caesar dressing, with crunchy croutons and shaved Parmesan.',
    isAvailable: true,
  },
  {
    id: 'app7',
    name: 'Chicken Caesar Salad',
    price: 355,
    category: 'appetizers',
    image: saladImg(),
    description: 'Classic Caesar salad topped with tender grilled chicken strips, croutons, and shaved Parmesan.',
    isAvailable: true,
  },
  {
    id: 'app8',
    name: 'Burrata Salad',
    price: 385,
    category: 'appetizers',
    image: pizzaImg,
    description: 'Creamy burrata cheese served over a bed of fresh arugula, cherry tomatoes, and black olives, drizzled with extra virgin olive oil.',
    isAvailable: true,
  },
  {
    id: 'app9',
    name: 'Cheese Chicken Arancini',
    price: 345,
    category: 'appetizers',
    image: pastaImg,
    description: 'Golden-fried Italian risotto balls stuffed with chicken and molten cheese, crispy outside and creamy inside.',
    isAvailable: true,
  },
  {
    id: 'app10',
    name: 'Cocktail Shrimp Salad',
    price: 395,
    category: 'appetizers',
    image: saladImg(),
    description: 'Fresh succulent shrimp with crisp green lettuce, red paprika, lemon juice, cherry tomatoes, and olive oil.',
    isAvailable: true,
  },
  {
    id: 'app11',
    name: 'Caprese Dip With Assorted Breads',
    price: 345,
    category: 'appetizers',
    image: pizzaImg,
    description: 'A rich dip of olive oil, balsamic vinegar, olives, sun-dried tomatoes, garlic, paprika, and parmesan served with warm breads.',
    isAvailable: true,
  },

  // --- PIZZA ---
  {
    id: 'pz1',
    name: 'Margherita',
    price: 425,
    category: 'pizza',
    image: pizzaImg,
    description: 'Classic combination of rich pomodoro tomato sauce, fresh mozzarella, and sweet basil leaves.',
    isAvailable: true,
  },
  {
    id: 'pz2',
    name: 'Cossaca',
    price: 435,
    category: 'pizza',
    image: pizzaImg,
    description: 'Traditional Neapolitan style with rich pomodoro sauce, fresh basil, and a generous dusting of Parmesan.',
    isAvailable: true,
  },
  {
    id: 'pz3',
    name: 'Marinara',
    price: 395,
    category: 'pizza',
    image: pizzaImg,
    description: 'A timeless minimalist recipe with rich pomodoro sauce, sliced garlic, and fragrant oregano.',
    isAvailable: true,
  },
  {
    id: 'pz4',
    name: 'E Funghi',
    price: 455,
    category: 'pizza',
    image: pizzaImg,
    description: 'Earthysavor with pomodoro sauce, sweet caramelized onions, field mushrooms, black pepper, and Parmesan.',
    isAvailable: true,
  },
  {
    id: 'pz5',
    name: 'Quattro Formaggi',
    price: 475,
    category: 'pizza',
    image: pizzaImg,
    description: 'A cheese lover’s dream with pomodoro, rich Parmesan, fresh mozzarella, creamy cream cheese, and cottage cheese.',
    isAvailable: true,
  },
  {
    id: 'pz6',
    name: 'Pesto Burratta',
    price: 565,
    category: 'pizza',
    image: pizzaImg,
    description: 'Vibrant basil pesto, rich pomodoro sauce, fresh arugula, and a whole creamy burrata cheese ball.',
    isAvailable: true,
  },
  {
    id: 'pz7',
    name: 'Pesto Prosciutto',
    price: 595,
    category: 'pizza',
    image: pizzaImg,
    description: 'Savory combination of basil pesto, pomodoro, fresh arugula, burrata, and tender chicken ham.',
    isAvailable: true,
  },
  {
    id: 'pz8',
    name: 'Diavola',
    price: 565,
    category: 'pizza',
    image: pizzaImg,
    description: 'Spicy pizza with pomodoro sauce, fiery chicken salami, chili peppers, and melted mozzarella.',
    isAvailable: true,
  },
  {
    id: 'pz9',
    name: 'Salame Picante',
    price: 545,
    category: 'pizza',
    image: pizzaImg,
    description: 'Classic pepperoni style with rich pomodoro sauce, spicy chicken pepperoni, and grated Parmesan.',
    isAvailable: true,
  },
  {
    id: 'pz10',
    name: 'Chicken Roma',
    price: 545,
    category: 'pizza',
    image: pizzaImg,
    description: 'Delicious pulled chicken, rich pomodoro sauce, mozzarella, and a tangy BBQ sauce drizzle.',
    isAvailable: true,
  },
  {
    id: 'pz11',
    name: 'Bolognese',
    price: 625,
    category: 'pizza',
    image: pizzaImg,
    description: 'Hearty meat pizza featuring slow-cooked lamb Bolognese sauce, fresh basil, and Parmesan.',
    isAvailable: true,
  },
  {
    id: 'pz12',
    name: 'Cacio E Pepe Pizza',
    price: 495,
    category: 'pizza',
    image: pizzaImg,
    description: 'A white pizza based on the classic pasta dish, with mozzarella, cracked black pepper, and olive oil.',
    isAvailable: true,
  },
  {
    id: 'pz13',
    name: 'Blanc',
    price: 515,
    category: 'pizza',
    image: pizzaImg,
    description: 'A creamy white base of rich béchamel, mozzarella, black olives, and aromatic Italian herbs.',
    isAvailable: true,
  },
  {
    id: 'pz14',
    name: 'Carbonara Pizza',
    price: 545,
    category: 'pizza',
    image: pizzaImg,
    description: 'Decadent white base pizza with rich béchamel, mozzarella, cracked black pepper, and chicken bacon.',
    isAvailable: true,
  },

  // --- PASTA & RISOTTO ---
  {
    id: 'pst1',
    name: 'Penne Alfredo',
    price: 425,
    category: 'pasta',
    image: pastaImg,
    description: 'Creamy Alfredo sauce made with butter, garlic, and parmesan tossed with penne pasta.',
    isAvailable: true,
  },
  {
    id: 'pst2',
    name: 'Farfalle Arrabbiata',
    price: 415,
    category: 'pasta',
    image: pastaImg,
    description: 'Bold and spicy tomato sauce with garlic, chili flakes, and olive oil, served over farfalle.',
    isAvailable: true,
  },
  {
    id: 'pst3',
    name: 'Linguine Pesto',
    price: 445,
    category: 'pasta',
    image: pastaImg,
    description: 'Basil pesto made in-house with olive oil, parmesan, and pine nuts, gently coating al dente linguine.',
    isAvailable: true,
  },
  {
    id: 'pst4',
    name: 'Shrimp Linguine',
    price: 535,
    category: 'pasta',
    image: pastaImg,
    description: 'Linguine tossed with sautéed shrimp, garlic, chili, and lemon in a white wine butter sauce.',
    isAvailable: true,
  },
  {
    id: 'pst5',
    name: 'Ravioli Pomodoro E Salvia',
    price: 495,
    category: 'pasta',
    image: pastaImg,
    description: 'Cheese-stuffed ravioli served in a fresh tomato and sage butter sauce.',
    isAvailable: true,
  },
  {
    id: 'pst6',
    name: 'Lasagna',
    price: 495,
    category: 'pasta',
    image: pastaImg,
    description: 'Layered pasta sheets with béchamel, cheese, and slow-cooked tomato sauce; oven-baked until golden.',
    isAvailable: true,
  },
  {
    id: 'pst7',
    name: 'Spaghetti Aglio E Olio',
    price: 445,
    category: 'pasta',
    image: pastaImg,
    description: 'Simple and flavorful spaghetti with garlic, olive oil, chili flakes, and parsley.',
    isAvailable: true,
  },
  {
    id: 'pst8',
    name: 'Bolognese Lamb',
    price: 615,
    category: 'pasta',
    image: pastaImg,
    description: 'Slow-cooked lamb mince in a rich tomato and herb sauce served over spaghetti.',
    isAvailable: true,
  },
  {
    id: 'pst9',
    name: 'Mac & Cheese',
    price: 455,
    category: 'pasta',
    image: pastaImg,
    description: 'Classic elbow macaroni in a velvety cheese sauce, baked with a golden crust of cheddar.',
    isAvailable: true,
  },
  {
    id: 'pst10',
    name: 'Gnocchi Parma',
    price: 465,
    category: 'pasta',
    image: pastaImg,
    description: 'Soft potato pasta served in a rich, velvety Parmesan cream sauce with a hint of herbs.',
    isAvailable: true,
  },
  {
    id: 'pst11',
    name: 'Green Risotto',
    price: 445,
    category: 'pasta',
    image: pastaImg,
    description: 'Creamy Arborio rice infused with fresh basil pesto and finished with Parmesan.',
    isAvailable: true,
  },
  {
    id: 'pst12',
    name: '999 Silver Truffle Risotto',
    price: 495,
    category: 'pasta',
    image: pastaImg,
    description: 'Creamy risotto infused with truffle essence and finished with Parmesan for an elegant touch.',
    isAvailable: true,
  },
  {
    id: 'pst13',
    name: 'Rigatoni Ala Vodka',
    price: 525,
    category: 'pasta',
    image: pastaImg,
    description: 'Rigatoni pasta tossed in a rich and creamy tomato-vodka sauce, finished with parmesan and fresh herbs.',
    isAvailable: true,
  },
  {
    id: 'pst14',
    name: 'Pasta Alla Ruota',
    price: 725,
    category: 'pasta',
    image: pastaImg,
    description: 'Authentic preparation of al dente pasta tossed inside a giant wheel of cheese for maximum creaminess.',
    isAvailable: true,
  },

  // --- PANINI ---
  {
    id: 'pan1',
    name: 'Mediterranean Panini',
    price: 425,
    category: 'panini',
    image: sandwichImg,
    description: 'Baked panini filled with roasted bell peppers, olives, sun-dried tomatoes, and cream cheese, finished with pesto spread.',
    isAvailable: true,
  },
  {
    id: 'pan2',
    name: 'Mushroom Delight Panini',
    price: 425,
    category: 'panini',
    image: sandwichImg,
    description: 'A warm, pressed sandwich with sautéed mushrooms, caramelized onions, cheese, and herbed garlic butter.',
    isAvailable: true,
  },
  {
    id: 'pan3',
    name: 'Gourmet Chicken Panini',
    price: 495,
    category: 'panini',
    image: sandwichImg,
    description: 'Chicken ham, chicken bacon with cheddar, jalapeños, and a smoky BBQ sauce pressed in artisanal bread.',
    isAvailable: true,
  },
  {
    id: 'pan4',
    name: 'Chicken Supreme Panini',
    price: 475,
    category: 'panini',
    image: sandwichImg,
    description: 'Juicy chicken salami, bell peppers, mozzarella, and zesty dressing grilled to perfection in a crusty panini.',
    isAvailable: true,
  },

  // --- HOT DRINKS ---
  {
    id: 'ht1',
    name: 'Espresso',
    price: 119,
    category: 'hot',
    image: espressoImg,
    description: 'A rich and intense 30ml shot of pure espresso.',
    isAvailable: true,
  },
  {
    id: 'ht2',
    name: 'Doppio',
    price: 139,
    category: 'hot',
    image: espressoImg,
    description: 'A double shot (60ml) of intense, aromatic espresso.',
    isAvailable: true,
  },
  {
    id: 'ht3',
    name: 'Cortado',
    price: 169,
    category: 'hot',
    image: cappuccinoImg,
    description: 'Equal parts espresso and warm steamed milk (30ml each).',
    isAvailable: true,
  },
  {
    id: 'ht4',
    name: 'Macchiato',
    price: 179,
    category: 'hot',
    image: cappuccinoImg,
    description: 'A single shot of espresso marked with a dollop of milk foam.',
    isAvailable: true,
  },
  {
    id: 'ht5',
    name: 'Flat White',
    price: 209,
    category: 'hot',
    image: cappuccinoImg,
    description: 'Double espresso with smooth, velvety micro-foamed hot milk.',
    isAvailable: true,
  },
  {
    id: 'ht6',
    name: 'Americano',
    price: 199,
    category: 'hot',
    image: heroCoffee,
    description: 'A double shot of espresso diluted with hot water.',
    isAvailable: true,
  },
  {
    id: 'ht7',
    name: 'Mocha',
    price: 249,
    category: 'hot',
    image: heroCoffee,
    description: 'A decadent combination of chocolate syrup, rich espresso, and hot milk.',
    isAvailable: true,
  },
  {
    id: 'ht8',
    name: 'Latte',
    price: 239,
    category: 'hot',
    image: heroCoffee,
    description: 'Espresso mixed with steamed milk and a light layer of milk foam.',
    isAvailable: true,
  },
  {
    id: 'ht9',
    name: 'Hazelnut Latte',
    price: 259,
    category: 'hot',
    image: heroCoffee,
    description: 'Our classic espresso and steamed milk latte infused with hazelnut syrup.',
    isAvailable: true,
  },
  {
    id: 'ht10',
    name: 'Caramel Latte',
    price: 289,
    category: 'hot',
    image: heroCoffee,
    description: 'Our classic espresso and steamed milk latte infused with sweet caramel syrup.',
    isAvailable: true,
  },
  {
    id: 'ht11',
    name: 'Nutella Latte',
    price: 289,
    category: 'hot',
    image: heroCoffee,
    description: 'Our classic latte upgraded with a delicious swirl of rich Nutella.',
    isAvailable: true,
  },
  {
    id: 'ht12',
    name: 'Cappuccino',
    price: 229,
    category: 'hot',
    image: cappuccinoImg,
    description: 'A balanced mix of espresso, steamed milk, and a thick layer of milk foam.',
    isAvailable: true,
  },

  // --- ICED DRINKS ---
  {
    id: 'ic1',
    name: 'Iced Latte',
    price: 249,
    category: 'iced',
    image: icedCoffee,
    description: 'Rich espresso poured over ice and cold milk.',
    isAvailable: true,
  },
  {
    id: 'ic2',
    name: 'Iced Americano',
    price: 229,
    category: 'iced',
    image: icedCoffee,
    description: 'Espresso shots poured over ice and cold water.',
    isAvailable: true,
  },
  {
    id: 'ic3',
    name: 'Iced Mocha',
    price: 289,
    category: 'iced',
    image: icedCoffee,
    description: 'Espresso blended with rich chocolate, poured over cold milk and ice.',
    isAvailable: true,
  },
  {
    id: 'ic4',
    name: 'Iced Caramel Latte',
    price: 279,
    category: 'iced',
    image: icedCoffee,
    description: 'Chilled latte flavored with sweet, buttery caramel syrup.',
    isAvailable: true,
  },
  {
    id: 'ic5',
    name: 'Iced Hazelnut Latte',
    price: 279,
    category: 'iced',
    image: icedCoffee,
    description: 'Chilled latte flavored with premium aromatic hazelnut syrup.',
    isAvailable: true,
  },
  {
    id: 'ic6',
    name: 'Iced Nutella Latte',
    price: 299,
    category: 'iced',
    image: icedCoffee,
    description: 'Chilled latte blended with rich, creamy Nutella chocolate.',
    isAvailable: true,
  },

  // --- COLD CLASSICS ---
  {
    id: 'cld1',
    name: "Luca's Classic Cold Coffee",
    price: 259,
    category: 'cold',
    image: icedCoffee,
    description: 'Our signature chilled, creamy blended coffee classic.',
    isAvailable: true,
  },
  {
    id: 'cld2',
    name: 'Caramel Cold Coffee',
    price: 279,
    category: 'cold',
    image: icedCoffee,
    description: 'Chilled, creamy blended coffee enhanced with rich caramel.',
    isAvailable: true,
  },
  {
    id: 'cld3',
    name: 'Hazelnut Cold Coffee',
    price: 279,
    category: 'cold',
    image: icedCoffee,
    description: 'Chilled, creamy blended coffee enhanced with smooth hazelnut.',
    isAvailable: true,
  },

  // --- LUCA'S SIGNATURE ---
  {
    id: 'sig1',
    name: 'Chocolate Calda',
    price: 299,
    category: 'signature',
    image: heroCoffee,
    description: 'Rich, thick, and velvety Italian hot chocolate served warm.',
    isAvailable: true,
  },
  {
    id: 'sig2',
    name: 'Cold Cocoa',
    price: 329,
    category: 'signature',
    image: icedCoffee,
    description: 'Smooth, creamy, and decadent chilled chocolate beverage.',
    isAvailable: true,
  },
  {
    id: 'sig3',
    name: 'Traditional Matcha',
    price: 249,
    category: 'signature',
    image: mocktailImg,
    description: 'Authentic whisked Japanese stone-ground matcha green tea.',
    isAvailable: true,
  },
  {
    id: 'sig4',
    name: 'Matcha Latte',
    price: 279,
    category: 'signature',
    image: cappuccinoImg,
    description: 'Traditional Japanese matcha prepared with steamed milk.',
    isAvailable: true,
  },
  {
    id: 'sig5',
    name: 'Iced Matcha Latte',
    price: 279,
    category: 'signature',
    image: icedCoffee,
    description: 'Chilled whisked matcha served with ice and cold milk.',
    isAvailable: true,
  },
  {
    id: 'sig6',
    name: 'Iced Strawberry Matcha',
    price: 299,
    category: 'signature',
    image: icedCoffee,
    description: 'Matcha layered with home-made strawberry compote and cold milk.',
    isAvailable: true,
  },
  {
    id: 'sig7',
    name: 'Iced Matcha Cloud',
    price: 329,
    category: 'signature',
    image: mocktailImg,
    description: 'Matcha green tea layered with pure coconut water and light foam.',
    isAvailable: true,
  },
  {
    id: 'sig8',
    name: 'Iced Tiramisu Latte',
    price: 329,
    category: 'signature',
    image: icedCoffee,
    description: 'Iced espresso latte layered with a rich, velvety tiramisu foam topper.',
    isAvailable: true,
  },
  {
    id: 'sig9',
    name: 'Espresso Tonic',
    price: 249,
    category: 'signature',
    image: mocktailImg,
    description: 'A double shot of espresso floated over chilled premium tonic water.',
    isAvailable: true,
  },
  {
    id: 'sig10',
    name: 'Berry Espresso',
    price: 249,
    category: 'signature',
    image: mocktailImg,
    description: 'Espresso shot with a sweet, tangy berry infusion over ice.',
    isAvailable: true,
  },
  {
    id: 'sig11',
    name: 'Orange Espresso',
    price: 249,
    category: 'signature',
    image: mocktailImg,
    description: 'Double shot of espresso combined with fresh squeezed orange juice.',
    isAvailable: true,
  },

  // --- NOT COCKTAILS (MOCKTAILS) ---
  {
    id: 'nc1',
    name: 'New York Sour Mocktail',
    price: 345,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'A sophisticated blend of sober non-alcoholic whiskey, fresh lemon juice, and sweet grenadine.',
    isAvailable: true,
  },
  {
    id: 'nc2',
    name: 'Old Fashioned Mocktail',
    price: 345,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic whiskey, aromatic bitters, sugar, and ice garnished with citrus peel.',
    isAvailable: true,
  },
  {
    id: 'nc3',
    name: 'Cuban Mocktail',
    price: 335,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'A refreshing Mojito-style blend with sober non-alcoholic rum, lime, sugar, and fresh mint.',
    isAvailable: true,
  },
  {
    id: 'nc4',
    name: 'Negroni Mocktail',
    price: 345,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'A bitter, herbal blend with sober non-alcoholic rum and our special bitter harmony.',
    isAvailable: true,
  },
  {
    id: 'nc5',
    name: 'Dark & Stormy Mocktail',
    price: 325,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic rum paired with spicy ginger ale and a squeeze of fresh lime.',
    isAvailable: true,
  },
  {
    id: 'nc6',
    name: 'Basil Smash Mocktail',
    price: 325,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic gin, freshly muddled basil leaves, and tangy lime juice.',
    isAvailable: true,
  },
  {
    id: 'nc7',
    name: 'Gin & Tonic Mocktail',
    price: 315,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Crisp, refreshing botanical blend with sober non-alcoholic gin and premium tonic.',
    isAvailable: true,
  },
  {
    id: 'nc8',
    name: 'Espresso Martini Mocktail',
    price: 325,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic gin, freshly pulled espresso shot, bitters, and sugar shaken with ice.',
    isAvailable: true,
  },
  {
    id: 'nc9',
    name: 'Love Tonic Mocktail',
    price: 325,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic pink gin, tonic water, and a delicate splash of organic rosewater.',
    isAvailable: true,
  },
  {
    id: 'nc10',
    name: 'Rasberripolitan Mocktail',
    price: 355,
    category: 'not-cocktails',
    image: mocktailImg,
    description: 'Sober non-alcoholic pink gin, tart wild berry juice, and a squeeze of fresh lime.',
    isAvailable: true,
  },

  // --- SOFT BEVERAGES ---
  {
    id: 'sb1',
    name: 'Iced Tea - Peach or Lemon',
    price: 199,
    category: 'soft-beverages',
    image: mojitoImg,
    description: 'Classic chilled tea served over ice with your choice of sweet peach or tangy lemon flavor.',
    isAvailable: true,
  },
  {
    id: 'sb2',
    name: 'Aerated Beverages (Diet Coke / Sprite)',
    price: 119,
    category: 'soft-beverages',
    image: mojitoImg,
    description: 'Your choice of ice-cold Diet Coke or Sprite.',
    isAvailable: true,
  },
  {
    id: 'sb3',
    name: 'Redbull',
    price: 169,
    category: 'soft-beverages',
    image: mojitoImg,
    description: 'Premium chilled energy drink to boost your day.',
    isAvailable: true,
  },
  {
    id: 'sb4',
    name: 'Fresh Juice (Orange / Watermelon)',
    price: 219,
    category: 'soft-beverages',
    image: mojitoImg,
    description: '100% freshly squeezed seasonal orange or watermelon juice.',
    isAvailable: true,
  },
  {
    id: 'sb5',
    name: 'Ginger Ale',
    price: 169,
    category: 'soft-beverages',
    image: mojitoImg,
    description: 'Premium ginger ale beverage served chilled.',
    isAvailable: true,
  },

  // --- DESSERTS ---
  {
    id: 'ds1',
    name: 'Nutella Hazelnut Brownie',
    price: 325,
    category: 'dessert',
    image: waffleImg,
    description: 'Rich, fudgy chocolate brownie topped with thick Nutella and roasted hazelnuts.',
    isAvailable: true,
  },
  {
    id: 'ds2',
    name: 'Classic Tiramisu',
    price: 335,
    category: 'dessert',
    image: waffleImg,
    description: 'Traditional Italian dessert with coffee-soaked ladyfingers, creamy mascarpone, and cocoa dust.',
    isAvailable: true,
  },
  {
    id: 'ds3',
    name: 'Dark Chocolate Mousse With Crumble',
    price: 295,
    category: 'dessert',
    image: waffleImg,
    description: 'Silky smooth dark chocolate mousse served with a crunchy biscuit crumble bottom.',
    isAvailable: true,
  },
  {
    id: 'ds4',
    name: 'Vanilla Affogato',
    price: 215,
    category: 'dessert',
    image: cappuccinoImg,
    description: 'A scoop of premium vanilla ice cream drowned in a hot shot of double espresso.',
    isAvailable: true,
  },
  {
    id: 'ds5',
    name: 'Butter Croissant',
    price: 215,
    category: 'dessert',
    image: croissant,
    description: 'Crispy, flaky, and buttery French pastry baked daily.',
    isAvailable: true,
  },
];

// Helper to provide a fallback image for salads or green dishes
function saladImg() {
  return croissant;
}
